---
abstract: 'Queues with leaky buckets'
author:
  - 'Taro Funaki <t@33rpm.jp>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Queue-Leaky
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  Queue::Base: 0
version: 0.01
